
.INCLUDE "m328Pdef.inc"

.EQU END_MSJ = 0X5C	;Codigo ASCCI para caracter '\' 

.EQU POS_LED1 = 1
.EQU POS_LED2 = 5
.EQU POS_LED3 = 3
.EQU POS_LED4 = 4

.EQU PUERTO_SALIDA = PORTB
.EQU DDR_SALIDA = DDRB

.ORG 0X100
TABLA_ROM_MSJ: .DB 0b00001010, "*** Hola Labo de Micro ***", 0b00001010
TABLA_ROM_OPT: .DB 0b00001010, "Escriba 1, 2, 3 o 4 para controlar los LEDs \ "

.ORG 0x00
	RJMP MAIN

MAIN:
	LDI R16, HIGH(RAMEND)	
	OUT SPH, R16
	LDI R16, LOW(RAMEND)
	OUT SPL, R16

	LDI R16, 0xFF
	OUT DDR_SALIDA, R16	

	LDI R16,(1<<RXEN0)|(1<<TXEN0)|(1<<UCSZ02) ;Se habilita transmision y recepcion
	STS UCSR0B, R16
	LDI R16,(1<<UCSZ01)|(1<UCSZ00) ;Parity deshabilitado, 9 bits,
	STS UCSR0C, R16
	LDI R16, 103	; Baud Rate = 9600
	STS UBRR0L, R16

	LDI ZH, HIGH(TABLA_ROM_MSJ <<1)	;Apunto hacia la tabla con MENSAJE
	LDI ZL, LOW(TABLA_ROM_MSJ <<1)


LOOP:
	LPM R17, Z+		;Se almacena el valor de la tabla ROM en R17
	CPI R17, END_MSJ	;Se compara con el caracter final
	BREQ END_MESSAGE	;Si termino la lectura se manda el siguiente mensaje

TRANSMIT:
	LDS R16,UCSR0A
	SBRS R16,UDRE0		;Esta el buffer listo para transmitir?
	RJMP TRANSMIT		;Si no lo esta, se espera
	STS UDR0,R17	
	RJMP LOOP	

END_MESSAGE:

READ:
	LDS R16,UCSR0A  
	SBRS R16,RXC0	    ;Verifico si se recibio algun mensaje	
	RJMP READ			
OPTIONS:                
	LDS R18,UDR0        ;Leo el dato recibido y comparo
	CPI R18, 0x31			
	BREQ ENCENDER_UNO		
	CPI R18, 0x32			
	BREQ ENCENDER_DOS		
	CPI R18, 0x33			
	BREQ ENCENDER_TRES	
	CPI R18, 0x34			
	BREQ ENCENDER_CUATRO	
	RJMP READ				
	
ENCENDER_UNO:
	SBIS PUERTO_SALIDA, POS_LED1	
	RJMP ENCENDER1			
	RJMP APAGAR1
ENCENDER1:
	SBI PUERTO_SALIDA, POS_LED1
	CALL DELAY
	RJMP READ
APAGAR1:
	CBI PUERTO_SALIDA,POS_LED1
	CALL DELAY
	RJMP READ


ENCENDER_DOS:
	SBIS PUERTO_SALIDA, POS_LED2
	RJMP ENCENDER2		
	RJMP APAGAR2
ENCENDER2:
	SBI PUERTO_SALIDA, POS_LED2
	CALL DELAY
	RJMP READ
APAGAR2:
	CBI PUERTO_SALIDA,POS_LED2
	CALL DELAY
	RJMP READ

ENCENDER_TRES:
	SBIS PUERTO_SALIDA, POS_LED3	
	RJMP ENCENDER3			
	RJMP APAGAR3
ENCENDER3:
	SBI PUERTO_SALIDA, POS_LED3
	CALL DELAY
	RJMP READ
APAGAR3:
	CBI PUERTO_SALIDA,POS_LED3
	CALL DELAY
	RJMP READ

ENCENDER_CUATRO:
	SBIS PUERTO_SALIDA, POS_LED4
	RJMP ENCENDER4		
	RJMP APAGAR4
ENCENDER4:
	SBI PUERTO_SALIDA, POS_LED4
	CALL DELAY
	RJMP READ
APAGAR4:
	CBI PUERTO_SALIDA,POS_LED4
	CALL DELAY
	RJMP READ

DELAY:
; Delay 60 000 cycles
; 3.75ms at 16.0 MHz
   LDI  R20, 60
L1:LDI  R21, 4
L2:LDI  R22, 250
L3:DEC  R22
   BRNE L3		
   DEC  R21
   BRNE L2			
   DEC  R20
   BRNE L1			
   RET
